### ISSUE TITLE
CI pipeline tool spike

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#1022]
Due to the sunsetting of SnapCI, we now have to look elsewhere for a CI tool.

## Acceptance Criteria

Have a assessment of benefits of each tool.

## In Scope

Transfer our pipeline to alternative tools that fulfill at least the following:
* Integrate with Github
* Integrate with pull requests

Some tools we already discussed were:
* Travis
* CircleCI

**Comment by FrailWords** [comment]
Tulio & I spiked on CircleCI.  We could complete the build with a `circle.yml` file with the following contents - 

```
machine:
  python:
    version:
      2.7
  node:
    version:
      6.1.0
  environment:
    LC_ALL: 'en_US.UTF-8'

dependencies:
  override:
    - make clean_all
    - pip install -U --force-reinstall --no-cache-dir virtualenv
    - gem install compass && rbenv rehash

test:
  override:
    - make linters
    - make test
    - make functional_tests_ci
```
